pipeline {
  agent any

  environment {
    registry = "yuhi1314/phpk8s"
    registry_fl = "yuhi1314/fluentd-agent"
    registryCredential = 'b53f99dc-0066-457d-af6c-79cc14a27442'
    dockerImage = ''
  }
  tools {
    jdk 'jdk11'
    maven 'maven'
  }

  stages {
    stage("Git Checkout") {
      steps {
        script {
          git branch: 'exam', url: 'https://github.com/yuhi1314/codeby-devops.git'
        }
      }
    }

    stage("Maven Build") {
      steps {
        script {
          sh "mvn clean install -T 1C" // -T 1C is used to speed up the build using multithreading
        }
      }
    }
    
    stage("Test Cases") {
      steps {
        sh "mvn test"
      }
    }

    stage('Building our image') {
      steps {
        script  {
            dockerImage = docker.build("${registry}:${BUILD_NUMBER}")
            docker.withRegistry('', registryCredential) {
              dockerImage.push()
          }
        }
      }
    }

    stage('Building our image with Dockerfile in fluentd folder') {
      steps {
        script {
          dir('exam_project/fluentd') {
            dockerImage = docker.build("${registry_fl}:${BUILD_NUMBER}")
            docker.withRegistry('', registryCredential) {
              dockerImage.push()
            }
          }
        }
      }
    }

    stage("Apply the Kubernetes files") {
      steps {
        script {
          sh "kubectl apply -f kubernetes/"
        }
      }
    }

    stage("Apply the Kubernetes files for monitoring") {
      steps {
        script {
          sh "kubectl apply -f monitoring/"
        }
      }
    }
  }
}
