apiVersion: v1
kind: ServiceAccount
metadata:
  name: diagnostic-tool-sa
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diagnostic-tool-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: diagnostic-tool-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: diagnostic-tool-clusterrole
subjects:
- kind: ServiceAccount
  name: diagnostic-tool-sa
  namespace: dev
---
apiVersion: v1
kind: Pod
metadata:
  name: diagnostic-tool-pod
  namespace: dev
spec:
  containers:
  - name: busybox
    image: busybox:1.30.1
    command: ["sleep", "3600"]
  serviceAccountName: diagnostic-tool-sa