---
- name: Install packages and start Nginx server
  hosts: all
  tasks:
    - name: Update APT package cache
      become: yes
      apt:
        update_cache: yes
    - name: Install wget, htop and nginx packages
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - wget
        - htop
        - nginx
    - name: Start Nginx service
      become: yes
      service:
        name: nginx
        state: started
- name: Display environment of the host
  hosts: all
  tasks:
    - name: Display environment
      debug:
        msg: "This host is in {{ ansible_env }}"
