apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: pv-node1 
spec: 
  capacity: 
    storage: 512Mi 
  volumeMode: Filesystem 
  accessModes: 
    - ReadWriteOnce 
  storageClassName: local-storage 
  local: 
    path: /mnt/data-node1 
  nodeAffinity: 
    required: 
      nodeSelectorTerms: 
      - matchExpressions: 
        - key: kubernetes.io/hostname 
          operator: In 
          values: 
          - multinode-m02
		  
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-node2
spec:
  capacity:
    storage: 512Mi 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /mnt/data-node2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - multinode-m03