name: CI

on:
  push:
    branches:
      - main

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build App1
        working-directory: lesson26/app_jenkins
        run: mvn -B -DskipTests clean package

      - name: Build App2
        working-directory: lesson26/app_devops
        run: mvn -B -DskipTests clean package

      - name: Build App3
        working-directory: lesson26/app_world
        run: mvn -B -DskipTests clean package

      - name: Test App1
        working-directory: lesson26/app_jenkins
        run: mvn test

      - name: Test App2
        working-directory: lesson26/app_devops
        run: mvn test

      - name: Test App3
        working-directory: lesson26/app_world
        run: mvn test

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-artifact
          path: |
            lesson26/app_jenkins/target/
            lesson26/app_devops/target/
            lesson26/app_world/target/

  build-docker-image:
    needs: build-test-package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image to GitHub Registry
        run: docker tag <commit_sha> ghcr.io/${{ github.repository }}/codeby-devops:${{ github.sha }}
      - run: docker push ghcr.io/${{ github.repository }}/codeby-devops:${{ github.sha }}




